name: act bug workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # To fetch all history for all branches and tags. Needed for git diff.

      - id: set_1
        run: |
          echo "::set-output name=var_1::$(echo hello)"

      - id: set_2
        run: |
          echo "::set-output name=var_2::$(echo world)"

      - name: set_3
        id: set_3
        uses: ./.github/actions/sample-action

      - name: print
        run: |
          echo "The diff output is: ${{ steps.set_1.outputs.var_1 }}"
          echo "The diff output is: ${{ steps.set_2.outputs.var_2 }}"
          echo "The diff output is: ${{ steps.set_3.outputs.var_3 }}"